<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "gskickstart"
 *
 * Auto generated by Extension Builder 2017-03-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'GS Kick-Start',
    'description' => 'GS Kick-Start allows you to install a customized Distribution.',
    'category' => 'distribution',
    'author' => 'Simon Gilli',
    'author_email' => 'typo3@gilbertsoft.org',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-8.99.99',
        ],
        'conflicts' => [],
        'suggests' => [
        	'introduction' => '*',
        	'aimeos_dist' => '*',
        	'gsprotectedconfig' => '*',
        	'gsfavicon' => '*',
        	'aimeos' => '*',
        	'bootstrap_package' => '*',
        	'realurl' => '*',
        ],
    ],
];
